apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/demos/rhoai-workshop-ready?ref=v0.11

patches:
  - target:
      kind: Subscription
      name: rhods-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: fast
  - target:
      kind: DataScienceCluster
    patch: |-
      - op: add
        path: /spec/components
        value:
          codeflare:
            managementState: Managed
          dashboard:
            managementState: Managed
          datasciencepipelines:
            managementState: Managed
          kserve:
            managementState: Managed
          kueue:
            managementState: Managed
          modelmeshserving:
            managementState: Managed
          ray:
            managementState: Managed
          trainingoperator:
            managementState: Managed
          trustyai:
            managementState: Managed
          workbenches:
            managementState: Managed
          modelregistry:
            managementState: Managed
            registriesNamespace: rhoai-model-registries
