apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/demos/overlays/rhoai-workshop-ready?ref=v0.12

patches:
  - target:
      kind: Subscription
      name: rhods-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: fast
  - target:
      kind: DataScienceCluster
    path: patch-dsc.yaml
  - target:
      kind: NodeFeatureDiscovery
    path: patch-node-feature-discovery.yaml
