apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: gpu-cluster-policy
spec:
  devicePlugin:
    config:
      default: time-sliced-8
      name: device-plugin-config
  gfd:
    enabled: true
