apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../components/advanced-cluster-management
- ../../components/advanced-cluster-security
- ../../components/branding
- ../../components/devspaces
- ../../components/htpasswd
- ../../components/minio
- ../../components/namespaces
- ../../components/rhoai-ready
- ../../components/web-terminal

patches:
  - target:
      kind: ConsoleNotification
      name: banner-demo
    patch: |-
      - op: replace
        path: /spec/text
        value: 'DEMO: OpenShift as an AI Platform'
