apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/tree/main/components/operators/devspaces/aggregate/overlays/nvidia-gpu?ref=v0.12