apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  annotations:
    controller.devfile.io/allow-import-from: '*'
    web-terminal.redhat.com/unmanaged-state: 'true'
  name: web-terminal-tooling
  namespace: openshift-operators
  labels:
    console.openshift.io/terminal: 'true'
spec:
  components:
    - container:
        args:
          - "/bin/bash"
          - "-c"
          - |
            #!/bin/bash

            echo "
            GIT_REPO=https://github.com/codekow/just-in-time-cluster

            [ -e ~/just-in-time-cluster ] || git clone \${GIT_REPO}
            [ -e ~/just-in-time-cluster ] && cd ~/just-in-time-cluster

            " >> /home/user/.bashrc

            . /home/user/.bashrc

            sleep infinity  # just in case

        cpuLimit: 400m
        cpuRequest: 100m
        image: ghcr.io/redhat-na-ssa/web-terminal-tooling:latest
        memoryLimit: 512Mi
        memoryRequest: 128Mi
        mountSources: false
        sourceMapping: /projects
      name: web-terminal-tooling
