apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/app-configs/minio/overlays/with-namespace-known-password?ref=v0.11

patches:
  - target:
      kind: PersistentVolumeClaim
      name: minio
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 40G
